realweb/urls.py
from django.contrib import admin
from django.urls import path
from realsite import views as mv
from django.conf import settings
from django.conf.urls.static import static
from realsite import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mv.homepage, name="homepage"),
    path('book/<str:book_name>/', mv.showbook, name='book_detail'),
    path('search/', mv.search_posts, name='search_posts'), 
    path('writer/<int:writer_id>/', views.writer_post, name='writer_post'),
    path('book/<int:book_id>/chapter/<int:chapter_id>/', mv.chapter_detail, name='chapter_detail'),
    path('book/<int:book_id>/rent/', mv.rent_or_return_book, name='rent_book'),
    path('book/<int:book_id>/edit_comment/<int:comment_id>/', views.edit_comment, name='edit_comment'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/', views.profile_view, name='profile'),
    path('', views.homepage, name='homepage'),
    path('renting_history/', views.renting_history, name='renting_history'),
    path('release_book/', views.release_book, name='release_book'),
    path('edit_user_added_books/', views.edit_user_added_books, name='edit_user_added_books'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

realsite/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User 

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    text = models.TextField()
    rating = models.PositiveIntegerField(choices=[(i, str(i)) for i in range(1, 6)])
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.title}"

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rented_books = models.ManyToManyField('Book', blank=True, related_name='user_rented_books')
    bio = models.TextField(blank=True)  

    def __str__(self):
        return self.user.username

    
class Writer(models.Model):
    creatorname = models.CharField(max_length=200, default='Name')
    
    MALE = 'Male'
    FEMALE = 'Female'
    GENDER_CHOICES = [
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    ]
    
    gender = models.CharField(
        max_length=10,
        choices=GENDER_CHOICES,
        default=MALE
    )
    
    born_date = models.DateField()
    
    age = models.PositiveIntegerField(
        validators=[
            MinValueValidator(1, message="Age must be at least 1."),
            MaxValueValidator(100, message="Age cannot exceed 100."),
        ]
    )
    
    image = models.ImageField(upload_to='writer_images/', blank=True, null=True)

    def __str__(self):
        return f'{self.age}-year-old {self.gender} writer'

class Book(models.Model):
    booktitle = models.CharField(max_length=200)
    picture = models.ImageField(upload_to='book_pictures/', blank=True, null=True)
    info = models.TextField()
    added_by = models.CharField(max_length=100, default="unknown")  
    creator = models.ForeignKey(Writer, on_delete=models.CASCADE) 
    release = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    available_copies = models.IntegerField(default=0)
    rented_by = models.ManyToManyField(User, related_name='rented_books', blank=True)
    
    STATUS_CHOICES = [
        ('Not Rented', 'Not Rented'),
        ('Rented', 'Rented'),
    ]
    
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='Not Rented',
    )

    def __str__(self):
        return self.booktitle

class Chapter(models.Model):
    book = models.ForeignKey('Book', on_delete=models.CASCADE, related_name='book_chapters')
    ctitle = models.CharField(max_length=200)
    title = models.CharField(max_length=255)
    story = models.TextField()
    chapter_number = models.IntegerField(default=0)

    def __str__(self):
        return self.title

templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>
            {% block title %}{% endblock %}
        </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        {% include "header.html" %}
        {% block headmessage %} {% endblock headmessage %}
        <hr>
        {% block content %}{% endblock content %}
        {% include "footer.html" %}
        <script scr="" async defer></script>
    </body>
</html>

templates/base2.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>
            {% block title %}{% endblock %}
        </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <div class="container-fluid">
            {% include 'header.html' %}
            <div class="row">
                <div class="col-sm-3 col-md-3">
                    <div class="card"> 
                    <div class="card-header">
                        <h3>MENU</h3>
                    </div>  
                    <div class="card-body">
                        <div class ='list-group'>
                            <a href="/" class="list-group-item">HOME</a>
                            <a href="https://google.com/news" class="list-group-item">Google news</a> 
                            <a href="https://www.youtube.com" class="list-group-item">Youtube</a>     
                            <a href="{% url 'edit_user_added_books' %}" class="list-group-item">Edit Book</a>
                            <a href="{% url 'release_book' %}" class="list-group-item">release book</a>
                            <a href="{% url 'register' %}" class="list-group-item">Register</a>
                            <a href="{% url 'login' %}" class="list-group-item">Login</a>
                            <a href="{% url 'edit_profile' %}" class="list-group-item">edit</a>
                            <a href="{% url 'renting_history' %}" class="list-group-item">Renting</a>
                        </div>
                        
                    </div>
                </div>
                </div>
            <div class="col-sm-7 col-md-5">
                <div class="card"> 
                    <div class="card-header">
                            {% block headmessage %} 
                            {% endblock %}
                    </div>
                    <div class="card-body">
                        {% block content %}
                        {% endblock content %}
                    </div>
                    <div class="card-footer">
                        {% include "footer.html" %}
                    </div>
                </div>
            </div>
        </div>
        
        <script scr="" async defer></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>

templates/chapter_detail.html
{% extends "base2.html" %}
{% load markdown_extras static %}

{% block headmessage %}
    <h3 style='font-family:微軟正黑體;'>Word hell</h3>
    <a style='font-family:微軟正黑體;' href='/'>Home</a>
{% endblock headmessage %}

{% block content %}
    <div class="book-details">
        <div class="text-details" style="float: left;">
            <p style="font-family:微軟正黑體; font-size:14pt; letter-spacing:2pt;">
                {{ chapter.story }} 
            </p>
        
        </div>
    </div>
    <div style="clear: both;"></div>
{% endblock content %}

templates/edit_comment.html
{% extends "base.html" %}
{% block content %}
<h2>Edit Comment</h2>
<form method="post">
    {% csrf_token %}
    <textarea name="new_comment">{{ book.comments }}</textarea>
    <input type="submit" value="Update Comment">
</form>
{% endblock %}

templates/edit_profile.html
{% extends "post.html" %} 
{% block content %}

<h2>Edit Profile</h2>


{% if form.errors %}
    <p>Your form has errors, please check below:</p>
{% endif %}


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

 
    <div>
        <label for="id_username">Username:</label>
        <input type="text" name="username" id="id_username" value="{{ user.username }}" readonly/>
    </div>


    <div>
        <label for="id_bio">Bio:</label>
        <textarea name="bio" id="id_bio">{{ form.bio.value|default_if_none:user.userprofile.bio }}</textarea>
    </div>

    <button type="submit">Save Changes</button>
</form>

{% endblock %}

templates/edit_user_added_books.html
{% extends "post.html" %}

{% block content %}
  <h2>Edit User Added Books</h2>
  <form method="post">
    {% csrf_token %}
    
    {% for book in user_added_books %}
      <div class="book-entry">
        {{ book.title }} by {{ book.author }}
        <input type="hidden" name="book_id" value="{{ book.id }}">
        
        <label for="id_booktitle">Title:</label>
        <input type="text" name="booktitle" value="{% if book_form.booktitle.value %}{{ book_form.booktitle.value }}{% else %}{{ book.booktitle }}{% endif %}">
        
        <label for="id_info">info:</label>
        <textarea name="info">{% if book_form.info.value %}{{ book_form.info.value }}{% else %}{{ book.info }}{% endif %}</textarea>

        <label for="id_available_copies">Number Left:</label>
        <input type="number" name="available_copies" value="{% if book_form.available_copies.value %}{{ book_form.available_copies.value }}{% else %}{{ book.available_copies }}{% endif %}">
        
        <label for="id_status">Status:</label>
        <select name="status">
          <option value="Not Rented" {% if book_form.status.value == "Not Rented" %}selected{% endif %}>Not Rented</option>
          <option value="Rented" {% if book_form.status.value == "Rented" %}selected{% endif %}>Rented</option>
        </select>
        
        <button type="submit">Save Changes</button>
      </div>
    {% endfor %}
  </form>
  <a href="{% url 'homepage' %}">Home</a>
{% endblock %}

templates/footer.html
{% block footer %}
    {% if now %}
    <p style = 'font-family:微軟正黑體;'>Time now :{{now}}</p>
    {% else%}
    <p style ='font-family:微軟正黑體;'>All content is taken from online if needed please call for take down.</p>
    {% endif %}
{% endblock %}

templates/general_book.html
<html>
<head>
    <title>General Book Information</title>
</head>
<body>
    <h1>General Book Information</h1>
    <p>This is the general content for books.</p>
</body>
</html>

templates/header.html
{% load static %}
{% include 'search_form.html' %}
<!DOCTYPE html>
<html>
<head>

    <style>
        body {
            margin: 0; 
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            background: url("{% static 'images/grass-border-vector-illustration_433751-81.jpg' %}") no-repeat center center fixed;
            background-size: cover;
        }

        h1 {
            font-family: 微軟正黑體;
        }
    </style>
</head>
<body>
    <h1>11056050 陳一吉</h1>
    {% if request.user.is_authenticated %}
        <p>Welcome, {{ request.user.username }}</p>
    {% endif %}
</body>
</html>

templates/index.html
<!DOCTYPE html>
{% extends "base2.html" %}
{% block title %}Welcome to word hell{% endblock title %}
{% block headmessage %}<h3 style="font-family:標楷體;"> Books</h3>{% endblock headmessage %}
{% block content %}

<div class='card-footer' style='background-color:#FFFFFF'></div>

{% for book in posts %}
<div class='card'>
    <div class='card-header'>
        <p style="font-family:微軟正黑體; font-size:14pt; font-weight:bold;">
            <a href="/book/{{ book.booktitle }}">{{ book.booktitle }}</a>
        </p>
    </div>
    <div class='card-body' style="background-color:#979797">
        <div class="book-image">
            <img src="{{ book.picture.url }}" alt="{{ book.booktitle }}" style="max-width: 100%; max-height: 200px;" />
        </div>
        <p>
          
        </p>
    </div>
    <div class='card-footer' style='background-color:#FFFFFF'></div>
    <p>
        posted: {{ book.pub_date | date:"Y M d, h:i:s" }}
    </p>

</div>
<br>
{% endfor %}
{% endblock content %}

templates/login.html
{% extends "post.html" %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">{{ form.title }}</div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/release_book.html
{% extends "post.html" %}

{% block content %}
  <h2>Release a New Book</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Release Book</button>
  </form>
  <a href="{% url 'book_list' %}">Back to Book List</a>
{% endblock %}

templates/rent_return_book.html
{% extends "post.html" %}

{% block content %}
<h2>Rent or Return Book</h2>
<form id="rent-return-form" action="{% url 'rent_or_return_book' book.id %}" method="post">
    {% csrf_token %}
    <button type="submit" name="action" value="rent">Rent Book</button>
    <button type="submit" name="action" value="return">Return Book</button>
</form>

<p id="result-message"></p>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        var form = document.getElementById('rent-return-form');
        form.addEventListener('submit', function(event) {
            event.preventDefault();
            var formData = new FormData(form);
            fetch(form.action, {
                method: 'POST',
                body: formData,
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}'
                },
            })
            .then(response => response.json())
            .then(data => {
                document.getElementById('result-message').textContent = data.message;
             
            })
            .catch(error => console.error('Error:', error));
        });
    });
</script>
{% endblock %}

templates/writer_post.html
{% extends "base2.html" %}
{% load markdown_extras static %}

{% block headmessage %}
    <h3 style='font-family:微軟正黑體;'> {{ writer.gender }} Writer</h3>
    <a style='font-family:微軟正黑體;' href='/'>Home</a>
{% endblock headmessage %}

{% block content %}
    <div class="book-details">
        <div class="picture-box">
            <img src="{{ writer.image.url }}" alt="{{ writer.gender }} Writer" style="max-width: 100%; max-height: 200px; float: left; margin-right: 20px;" />
        </div>
        <div class="text-details" style="float: left;">
            <p style="font-family:微軟正黑體; font-size:14pt; letter-spacing:2pt;">
                {{ writer.creatorname }} writer born on {{ writer.born_date | date:"Y M d" }}.
            </p>
            <p style="font-family:微軟正黑體; font-size:10pt; letter-spacing:2pt;">
                <strong>{{ writer.age }} years old</strong>
            </p>
        </div>
    </div>
    <div style="clear: both;"></div>
{% endblock content %}